#!/usr/bin/env bash

set -x            # print each command before execution
set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

git clone https://github.com/zeke/electron-download-stats
cd electron-download-stats
npm run build
npm test
[[ `git status --porcelain` ]] || exit
git add .
git config user.email "zeke@sikelianos.com"
git config user.name "Zeke Sikelianos"
git commit -m "update stats"
git push origin master --follow-tags
